### ISSUE TITLE
PR metrics dashboard

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1096]
PR latency histograms by size

**Comment by bgrant0607** [comment]
cc @kubernetes/contributor-experience

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/kubernetes/issues/24762

**Comment by apelisse** [comment]
I'm still working on that (and kubernetes#24762), but I'm trying to do it on the side so that I can make progress on contributor experience.

**Comment by bgrant0607** [comment]
@apelisse Please briefly summarize here what you are working on.

**Comment by bgrant0607** [comment]
I included some of Antoine's graphs here: https://groups.google.com/forum/#!topic/kubernetes-dev/MoyWB66vAKY

We're also going to run vossibility-stack.

**Comment by apelisse** [comment]
Here's what I'm doing in a few words:
- Github cache so that we can easily pull numbers without having to request from github
- InfluxDB time-series database to save relevant numbers
- Grafana to display charts

The goal is to be able to compute data from historic data, and create the most relevant metrics.

**Comment by apelisse** [comment]
Current output:
http://velodrome.kubernetes.io/dashboard/db/kubernetes-developer-velocity

**Comment by apelisse** [comment]
Code lives here: https://github.com/kubernetes/test-infra/tree/master/velodrome/

**Comment by bgrant0607** [comment]
Our metrics now live in devstats.k8s.io
