### ISSUE TITLE
cluster-autoscaler: We shouldn't delete nodes with pods with local storage

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/contrib#1162]
We shouldn't delete nodes which have pods with local storage like `emptyDir` or `hostPath`.

@piosz @jszczepkowski

**Comment by paurullan** [comment]
I know this issue is closed but is a popular destination for looking why your cluster is not downscaling. Most of our pods _had_ some kind of hostPath because we are using cloudsql-proxy and it mounts th e SSL certificates.

The easiest way seems to be using the "safe-to-evict" annotation.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

```
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"  
```
