### ISSUE TITLE
Ingress Controller doesn't handle very well when master is down

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/contrib#1226]
I just had to update the box where my Kubernetes master is running.
While the box was rebooting, the Ingress Controller lost all the secrets (TLS), and the HTTP basic auth configuration. In the end, all the Ingress Resources were just listening on 80. No more TLS, no more HTTP Basic Auth (and probably all the other configurations depending on annotations).

When master is not available, it shouldn't really update its nginx.conf. Thoughts ?

**Comment by bprashanth** [comment]
yeah. It should just coast along like the kubelet does and resync everything when the master is back up. 

This will probably result in a loss of endpoints for some time when the master comes back up though, because endpoints are marked unready after ~40s of the kubelet not being able to send health updates, and when the node "comes back online" at least one readiness check has to pass (depends on the interval params of the readiness probe) for it to show up as an endpoint.

**Comment by aledbf** [comment]
@edouardKaiser thanks for the report. Fix in the next version.

> When master is not available, it shouldn't really update its nginx.conf

Exactly. The issue here was related to a request during the sync without the proper error handling

**Comment by edouardKaiser** [comment]
That's great, thanks @aledbf
