### ISSUE TITLE
Better events for the gce ingress controller

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/contrib#1369]
At least: 
1. Service not found, because its common for people to try to ingress a service in a different namespace
2. Service doesn't have node port
3. What health check and port the url is using
4. tls cert issues (wrong keys in secret, bad certs)

**Comment by aknuds1** [comment]
I would rather like to be able to see logs from the ingress controller, so that I can trace why something isn't working. E.g., if your server is returning status 502, it can either come from the ingress controller itself or it might stem from the backend. There's no way of knowing what's going on since ingress controller won't say.

**Comment by bdimcheff** [comment]
Yeah I'm having a similar problem trying to figure out what's going on with health checks not honoring my readiness probe... I expected to see the pod in kube-system so I could get the logs, but I guess it's running on the master.

**Comment by bprashanth** [comment]
for the readiness probe, the ports need to match, i.e the port on the probe needs to match the container port which matches the target port on the service that you're plugging into the ingress (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks#limitations)

**Comment by bdimcheff** [comment]
I eventually got it working, but I ran into 2 problems along the way:

1. If you change the readiness probe in an RC, you have to delete and recreate the Service and the Ingress in order for the change to take effect.  I'm not sure what's caching this, but it definitely bit me a few times.
2. From what I can tell, using `host:` in the readiness probe is not supported and causes the probe to revert to the default.

In my particular case, the Ingress is pointed at a [service-loadbalancer](https://github.com/kubernetes/contrib/tree/master/service-loadbalancer), and if you don't specify a host, then haproxy will use the default backend and 404.  The 404 causes the health check to fail, so the ingress won't route traffic even though haproxy is perfectly healthy.  Since service-loadbalancer also mounts the service under `/servicename`, I can specify a path and it works fine, but ideally I'd be able to specify the host instead, since the http service checks support it.

**Comment by bprashanth** [comment]
I think both those are listed in the limitations:
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/examples/health_checks/README.md#limitations

We should throw an event. 

> I can specify a path and it works fine, but ideally I'd be able to specify the host instead, since the http service checks support i

Fwiw you can directly modify the health check through the gce console to include a host. This works for the same reason reconcilition on update doesn't work, we didn't do it to allow freedom for user to diverge params that might get introduced on the gce side and not reflect on the Kubernetes side (there was a time when gce didn't support host header in health probe).

**Comment by bdimcheff** [comment]
I think the implications of those limitations didn't really click.  It's definitely working as expected now, though.  Thanks for your help!
