### ISSUE TITLE
merge-bot not merging e2e-not-required PRs

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/contrib#140]
These are two e2e not required prs:

https://github.com/kubernetes/kubernetes/pull/14761
https://github.com/kubernetes/kubernetes/pull/14494

Merge bot comments (multiple times):

> Automatic merge from submit-queue

But the PRs are not merged.

cc @brendandburns @lavalamp @eparis

**Comment by lavalamp** [comment]
In the logs: 

```
E1002 00:38:55.882184       1 github.go:611] Failed to create merge comment: PUT https://api.github.com/repos/kubernetes/kubernetes/pulls/14761/merge: 405 Base branch was modified. Review and try the merge again. []
E1002 00:38:55.882298       1 submit-queue.go:159] Error running e2e test: PUT https://api.github.com/repos/kubernetes/kubernetes/pulls/14761/merge: 405 Base branch was modified. Review and try the merge again. []
```

**Comment by lavalamp** [comment]
Probably it just needs to re-ask for the mergability data in this case?

**Comment by brendandburns** [comment]
Yeah, those are github errors that happen when master is merged in the
middle of a attempt to merge a different PR.  I _think_ this only happens
if we manually merge things...

--brendan

**Comment by eparis** [comment]
Anyone know what commit of submit-queue is running?

**Comment by brendandburns** [comment]
It doesn't have your latest, it was built ~ last friday?

**Comment by eparis** [comment]
https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

I'll dig a little, I bet the go-github api is grabbing the merge HEAD sha and providing that in PUT request to the github api. In reality we don't want to provide that at all, instead of, as @lavalamp suggested, updating the mergability...

**Comment by eparis** [comment]
nope...  looks like the github API won't even take that SHA....   https://github.com/google/go-github/blob/master/github/pulls.go#L257

**Comment by lavalamp** [comment]
There's code in there that updates the mergability if it's not present,
right? Can we just rerun whatever that does if we get this error?

**Comment by eparis** [comment]
The 'mergeability' information isn't used at all here, updating it would do nothing (other than add a delay which might actually fix the problem). According to their docs we shouldn't get this message since we aren't passing a SHA in the merge request.

So I have no real/good idea...

**Comment by eparis** [comment]
My only guess is that this happens if we try to merge at the same instant that the 'mergeability' call would have returned nil. So we can either just wait 2 seconds and try again here, or we can use the IsMergeable() call.  The former seems more 'correct' but the later seems easier   :)

I'll code the later.

**Comment by lavalamp** [comment]
I see. SGTM

**Comment by mohammedri** [comment]
Was there ever a solution posted for this @eparis ?
