### ISSUE TITLE
Some imports being vendored and present in Godeps.

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1496]
I ran into this issue today when trying to get https://github.com/spf13/viper running with mungegithub. 

```
~/g/s/k/c/mungegithub (no-more-cmdline ⚡↩☡) set -x GO15VENDOREXPERIMENT 1; go build
# k8s.io/contrib/mungegithub
./mungegithub.go:52: cannot use cmd.Flags().Lookup("once") (type *"k8s.io/contrib/mungegithub/vendor/github.com/spf13/pflag".Flag) as type *"github.com/spf13/pflag".Flag in argument to viper.BindPFlag
```

The reason I saw now was that we [vendor the spf13/*](https://github.com/kubernetes/contrib/tree/master/mungegithub/vendor/github.com/spf13) imports and also have it in [godeps](https://github.com/kubernetes/contrib/blob/master/mungegithub/Godeps/Godeps.json#L89). Isn't this an anti-pattern, because it leads to situations like these when we mix vendored and non-vendored imports?

**Comment by eparis** [comment]
You mis-understand what `Godeps` is for. All that directory does is provide metadata to the `godep` tool about what is/should be in the `vendor` directory. There is nothing wrong with `godeps`.

If you use `vendor` (we do) you basically must vendor EVERYTHING. What's happening is that the mungegithub imports of cobra are being satisfied from `vendor` but since `viper` is outside of `vedor` its imports are being satisfied from your `GOPATH`.

Vendor viper into mungegithub and things will work.  This is a worse experience than using godep GOPATH rewriting in my opinion which solved all package deps with the same code (the first in GOPATH). But this is what golang chose to do...

**Comment by eparis** [comment]
basically, in mungegithub you need to do:
```
cd mungegithub
godep restore
go get -u github.com/spf13/viper
[add dependancy on viper inside mungegithub]
godep save ./...
```

**Comment by foxish** [comment]
I understand, and vendoring viper is what I ended up doing. I guess I didn't previously know that I shouldn't mix vendored imports with those I fetch from `godep restore`, which led me to this situation. I'd have expected both kinds of imports to be equivalent and interchangeable.

**Comment by eparis** [comment]
They were back under `godep go build` but the golang vendor experiment makes them solve differently. I don't like the behavior and think what you like makes more sense...

**Comment by thockin** [comment]
Go still supports multiple GOPATH entries,but it is hard to debug and not
reproducible, so just don't.

**Comment by eparis** [comment]
Define support?  If I put `dep1` in `vendor` and `dep2` in the GOPATH. If `dep2` uses `dep1` then `dep1` MUST also be in GOPATH and `GOPATH/dep1` with conflict/be different from `vendor/dep1`. I find it pretty horrible and that about 90% of people who run into the problem blame the wrong tools. Usually people blame `godep` which has nothing to do with it. Anyway, this is probably to support what CoreOS folks were doing with import path rewriting so one can have transitive vendored deps. I just don't like it. But this is not a bug/issue.
