### ISSUE TITLE
Submit-Queue race condition

### ISSUE THREAD

**Issue by tmrts** [kubernetes/contrib#1579]
See the comments by the bot for context in kubernetes/kubernetes#30996

After further examination, it seems to me that the problem is `retest-not-required`. When used, there is a race condition between merging and checking the PR. Here, the commit was merged immediately, but the PR wasn't closed so the bot saw a conflict because the commit was already merged and applied the label `needs-rebase`

cc @lavalamp @spxtr @kubernetes/test-infra-maintainers

**Comment by lavalamp** [comment]
@eparis @foxish @apelisse

**Comment by apelisse** [comment]
I can have a look at that, soon-ish

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/pull/30659 it happened here even without the `retest-not-required` label. It actually seemed like a GitHub bug. The PR was merged (I checked that the commits were in), but the PR was still "open" on the UI and API. It showed up as "needs rebase" because it was merged already! Then, an hour later or so, GitHub caught up.

**Comment by foxish** [comment]
Why do we not have protected branches check for submit-queue status marked as `required` in the main repo? It seems like only the e2e tests are set to required right now.
