### ISSUE TITLE
[ansible]ERROR! The requested handler 'restart daemons' was not found in any of the known handlers

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/contrib#1619]
Install with ansible, at last failed with error
```
TASK [kubernetes : Write the global config file] *******************************
ERROR! The requested handler 'restart daemons' was not found in any of the known handlers
```
Whole logs is : http://pastebin.test.redhat.com/405933

@ingvagabund

**Comment by ingvagabund** [comment]
This show up only when you use the ``github-release`` source type. Since the kubernetes config file is downloaded from [1]. With the package manager source type, the config file is generated from a template [2]. So at the end when you run the kubernetes-addons role with kubernetes role triggered as a dependency, the config file gets updated and thus the "restart deamon" notifier is run. At the end you end up with the same config (as the kubernetes role is run again). However, in the first case the notifier is needed, in the second one it is not.

[1] https://github.com/kubernetes/contrib/blob/master/init/systemd/environ/config
[2] https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/templates/config.j2

**Comment by ingvagabund** [comment]
The config issue is fixed here https://github.com/kubernetes/contrib/pull/1621
