### ISSUE TITLE
Nginx Ingress RC handles all namespace ingress

### ISSUE THREAD

**Issue by pdoreau** [kubernetes/contrib#1662]
Hello. I noticied that an nginx RC defined with namespace applies rules of an ingress defined in another namespace.

Is that nomral and desirable ?

**Comment by aledbf** [comment]
> Is that nomral and desirable ?

That is up to you. You can use the flag `--watch-namespace` to limit the watch to just one namespace.

**Comment by pdoreau** [comment]
Ok. It could be interesting to mention it in the README.
If the flag is used, does the default-backend has also to be defined with the same namespace ?

**Comment by aledbf** [comment]
>  does the default-backend has also to be defined with the same namespace ?

No

**Comment by pdoreau** [comment]
It seems I needed to create default-backend for each namespace I created an ingress with.
It works well, however I now have to many nginx RCs and they don't fit in my cluster (PodFitsHostPorts), see #1657

**Comment by aledbf** [comment]
> It seems I needed to create default-backend for each namespace I created an ingress with.

No need.

**Comment by aledbf** [comment]
> It works well, however I now have to many nginx RCs and they don't fit in my cluster (PodFitsHostPorts), see #1657

Right, you cannot scale the RC to a bigger number of the nodes in the cluster. Please check you are not running a different service that uses port 80 in the node/s

**Comment by bprashanth** [comment]
You can either: 
1. Run nginx controller with hostPort, in which case you can run only 1 per node, because theres exactly 1 hostPort (eg: 443) per node
2. Run nginx controller without hostPort, in which case you can only access it internally in cluster. You can run as many as you want per node.
3. Run nginx controller without hostPort, but expose it through a Service of Type.NodePort. In this case you can run as many nginx pods as you want, AND you can access it from outside, BUT you will get a random port, not 80/443, because that's how nodePort works. 

Please comment with questions if this is not clear
