### ISSUE TITLE
merge-bot is trying to merge already merged PR :)

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#167]
https://github.com/kubernetes/kubernetes/pull/15452#issuecomment-147714499

That PR was merge and 2 hours later merge-bot decided to retest it again.

cc @eparis @lavalamp

**Comment by eparis** [comment]
And now the merge bot is broken and won't merge anything else until it's restarted.

My guess on sequence of events.
- PR was added to the re-run e2e test queue.
- PR was given the e2e-not-required-label
- Munger ran a second time finding the PR was ready to merge and merged
- PR bubbled to the top of the e2e queue
- merge bot asked k8s-bot to test the PR
- k8s-bot obviously ignored us because the PR was merged
- merge bot will never timeout  :-(

@lavalamp @brendandburns please kick the submit queue bot. I'll fix the problem today.

**Comment by wojtek-t** [comment]
I restarted it.

**Comment by eparis** [comment]
Fixed By #169
