### ISSUE TITLE
Ingress GLBC: Default healthcheck used if readiness probe for different port

### ISSUE THREAD

**Issue by dominikschulz** [kubernetes/contrib#1681]
For a service/deployments exposing multiple ports the GLBC ingress may create the GCE backend healthchecks using the default path ("/") instead of the configured readiness probe.

We deployed a service exposing two ports (80 and 81) with a readiness probe configured as follows:
`        readinessProbe:
          httpGet:
            path: /healthz
            port: 81
          initialDelaySeconds: 10
          timeoutSeconds: 1
`

The GLBC ingress was configured to target the service port 80 and this led to the auto-created GCE healthcheck using "/" instead of "/healthz".

This fact should at least be mentioned in the documentation.

**Comment by jeroenvisser101** [comment]
We experienced the same yesterday and it caused downtime for us.

**Comment by jeroenvisser101** [comment]
To add on this, it seems like [it cannot find a healthcheck for the port here](https://github.com/kubernetes/contrib/blob/8cdbacdd66e9b1fe72e705beb9db4a695d2d249f/ingress/controllers/gce/healthchecks/healthchecks.go#L48-L55) and then falls back to the default port?

**Comment by bprashanth** [comment]
It always created a health check on "/", targetting the readiness probe is a recent modification, and only happens if it matches a set of requirements. Relevant docs: 
http://kubernetes.io/docs/user-guide/ingress/#before-you-begin
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/examples/health_checks/README.md#limitations

It falls back to the default *path* ("/"), the port is *always* the nodePort that matches the `servicePort` you specify in the Ingress, on GCE. This is different on other ingress controllers, which is why the first link in the docs above urges you to look up the relevant ingress controller docs. 

Please re-open if it's still an issue. Any prs to clarify docs are welcome.
