### ISSUE TITLE
Ingress can leverage healthCheckNodePort

### ISSUE THREAD

**Issue by kuroneko25** [kubernetes/contrib#1848]
Hi! I'm looking for a way to make Ingress/GLBC work when a different port is desired for the health check. Here is the context:
We run containers that contain Java gRPC services on GKE. When I set up GLBC I noticed that health checks are failing because the load balancer is making HTTP1.1 requests to the pods and our gRPC servers cannot handle HTTP1.1 requests. So I came up with a work-around by adding a side-car container that runs a HTTP server and proxies the health check requests from the LB to the gRPC server container. My service looks like this:

```
Name:           test-service
Namespace:      test
Labels:         name=test-service
Selector:               app=test-service
Type:           NodePort
IP:                 10.47.242.69
Port:           grpc    9000/TCP
NodePort:       grpc    31986/TCP
Endpoints:      10.44.0.17:1337
Port:           health-check    9001/TCP
NodePort:       health-check    32231/TCP
Endpoints:      10.44.0.17:1338
Session Affinity:   None
```

This works but requires manual configuration after the Ingress is created. Specifically I have to:
- Create a new health check in GCE that points to the node port 32231
- Create a new firewall rule that allows the LB to talk to the node port 32231
- Update the backend to use this new health check

Is it possible to make GLBC use a different port for health checking? Is there a better way to achieve what I want to do here?

**Comment by bprashanth** [comment]
Yeah I think we can, here's a brief sketch: 

We recently added an alpha feature that allows source ip preservation for type=lb loadbalancers. As part of that implementation we introduced an annotation called `healthCheckNodePort`, docs are: http://kubernetes.io/docs/user-guide/load-balancer/#annotation-to-modify-the-loadbalancer-behavior-for-preservation-of-source-ip

We can reuse the `healthCheckNodePort` with a different value for `external-traffic` such that kubeproxy doesn't spin up a health check on that port. The ingress will handle everything up to the port 32231. You will have to make sure that port 32231 serves healthy on every vm. This is already the case for you, since it looks like you'll just be plugging an existing nodePort in there.

**Comment by kuroneko25** [comment]
Just making sure I understand the proposal correctly:
- We'll be able to specify `healthCheckNodePort` as an annotation when defining a service of type `NodePort`. Can this value be the port name in a multi-port service or does it have to be the actual NodePort port number?
- GLBC will figure out that a different port should be used to create the health check when processing an Ingress. Nothing else changes except the backend now uses a health check on a port that is different from the servicePort in Ingress.

**Comment by bprashanth** [comment]
GLBC will point the health check at `healthCheckNodePort`, just like you did, and create the firewall rules. The port needs to serve health checks for the entire service. This part needs fleshing out since it is currently designed to fulfill a different purpose. 

Right now, `healthCheckNodePort` needs to be an actual port. It will graduate into a field of some sort. 

This is just one (probably most straightforward, least expressive) way to do it, we can also surface an entire health check block up in each backend section of the ingress.

**Comment by kuroneko25** [comment]
> The port needs to serve health checks for the entire service

So if I had an Ingress like 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-endpoint
  namespace: test
spec:
  rules:
  - http:
      paths:
      - path: /testservice
        backend:
          serviceName: test-service
          servicePort: 9000
      - path: /anotherservice
        backend:
          serviceName: another-service
          servicePort: 9001 
```
The health check port is responsible for serving health checks for both test-service and another-service?

**Comment by bprashanth** [comment]
no the healtCheckPort is on the service not the ingress

**Comment by kuroneko25** [comment]
Okay that makes sense. Any estimate when this is going to get fleshed out and eventually make to Beta/GA?
