### ISSUE TITLE
[gce ingress] Unable to use custom health checks

### ISSUE THREAD

**Issue by kyessenov** [kubernetes/contrib#1867]
We have a service that provides an API management interface. As is, it does not have "/" endpoint defined since that is dictated by OpenAPI interface specification that our service abides to. I have tried to specify a custom "liveness probe" on the pods backing the service:

livenessProbe:
        httpGet:
          path: /shelves
          port: 80

However, this is not picked up by the GCE ingress controller, and I see lots of 400s on / in the access log from my pods. I have also tried using a custom port (8090) since we have a status endpoint defined for it, but that also does not work. 

livenessProbe:
        httpGet:
          path: /nginx_status
          port: 8090

I have exposed both ports 80 and 8090 in my service spec.

Can you help me figure out why GCE ingress is not working? I cannot view the logs from GCE ingress pod since I'm using GKE and the load balancer seems to be running on the master.

**Comment by jojje** [comment]
We also hit the same problem. While waiting for your ticket to result in a proper fix, one workaround, and the one I personally employed for our env. was to add a special route processing directive in the nginx "cluster ingress service", exploiting the fact that GLBs perform health-check pings using node IP addresses and not hostnames. 

In _our_ setup all cluster services intended for external consumption are exposed by DNS names, and we can thus simply assume HTTP requests having an IP address in the request, rather than a DNS name, to originate from the GLB health-probes, and just redirect that kind of request to our ingress service's health-check URI / path. 

It's a hack, but one that allowed us to continue the environment building. Once this ticket is addressed, we'll just remove that special case (request processing config) and have the GLBs ping our intended health path.

**Comment by skylve** [comment]
@jojje Pretty interesting, how did you achieve that ? Could you give more info ?

I also tried to change the healthcheck configuration directly in GLBs but it didn't help, after a while the config is reseted to the default target (`/`) and defaults settings. I have no idea why.

**Comment by nuschk** [comment]
@skylve I wanted to go down that manual route as well. How fast did it change back? Mine is keeping its settings for 24h now...

Another alternative could be to add a simple http proxy to the pod in question and make it relay the request from '/' to wherever it needs to go. Seems the most simple way to do it and is probably what I will implement if I cannot override from gcloud.

**Comment by nuschk** [comment]
Guys, this *does* seem to work if you're not using named ports for mapping deployments to a service. Also, you need a readinessProbe instead of livenessProbe I guess.

Mine works now like this:

```
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
```

and is correctly mapped to a GCE healthcheck.

Also, as a reference, the example at https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks works as advertised on our cluster.

**Comment by skylve** [comment]
@nuschk you are right, just tried and it worked. Really nice !
Doesn't use the http headers though, but it's ok for now.
I guess the troubles started with my healthchecks when I updated my cluster version.

@kyessenov did you try with the `readinessProbe` ?

**Comment by kyessenov** [comment]
I have not tried `readinessProbe`. The example uses readiness probe, and it's tested, so that appears the way to go. Also, my troubles were caused by me editing live pods, and that's not picked up by the controller apparently. So that's something to watch out for, pods should have the probe from the creation time.
