### ISSUE TITLE
Cluster autoscaler: make sure that all pods present on the deleted node had a chance to be scheduled elsewhere

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#1898]
Otherwise next node deletion may be premature. We are not very likely to hit this issue right now although it is theoretically possible.

cc: @fgrzadkowski @piosz

**Comment by davidopp** [comment]
I think this should be flag-configured. Once we have disruption budget it may not be necessary.

**Comment by fgrzadkowski** [comment]
The reason to wait is not to avoid breaking disruption SLO, rather making sure that our simplified simulations are still valid. We want to avoid creating pending pods by scaling down the cluster.

**Comment by davidopp** [comment]
@fgrzadkowski I didn't understand your comment.

BTW there is no well-defined notion of a pod rescheduling elsewhere in Kubernetes (except maybe for instances of a PetSet).

**Comment by fgrzadkowski** [comment]
Sorry for not being clear. Let me try to clarify.

During simulation phase we check if a node could be deleted and all of the pods can be scheduled elsewhere. When we finally perform the scale down, before removing next node from a list, we should make sure that our simulation were accurate and indeed all the pods were correctly re-scheduled (i.e. recreated and scheduled somewhere else).

**Comment by mwielgus** [comment]
@fgrzadkowski - This is not exactly correct. We need to make sure that some pods from the rs/jobs/rc of the pods from the deleted nodes were created and had a chance to be scheduled.

The conditions would be:
* all rc/rs/jobs somehow involved in node deletion should have the correct number of pods created.
* there are no pods that have not been processed by the scheduler.

And actually we don't care whether our simulation was correct or not. It is too late.
We just want to make the next one as precise as possible.

**Comment by davidopp** [comment]
> all rc/rs/jobs somehow involved in node deletion should have the correct number of pods created.

I don't understand this requirement. Let's say the last scale-down resulted in a pending pod (i.e. the simulation was wrong). Why should that affect your decision of whether to do another scale-down? It doesn't seem the next simulation is more likely to be wrong just because the last one was wrong. (That said, maybe if you get two bad simulations in a row, you should stop the autoscaler and raise an alert.)

BTW note that with PodDisruptionBduget, strictly speaking you can do an eviction and not care whether the pod gets rescheduled, because the eviction would not have been allowed if that pod needs to be up. Of course, that's a very low bar, and people probably expect the system to behave better than that, but I just thought I'd mention it.

**Comment by mwielgus** [comment]
I wrote "created" because I want it to be created in the apiserver. It doesn't have to be scheduled, it can be marked as unschedulable. Deleting nodes while some rc/jobs/rs are yet to create pods in the apiserver (possibly in the place of nodes from the deleted node) is premature, the node may be needed in a few (milli) seconds. On the other hand, if a pod is marked as unschedulable then we know that the situation is more-or-less stable and the previously not needed node most likely won't be needed in the next second.

**Comment by mwielgus** [comment]
In theory all of these mechanisms are not needed. If CA is in sync with scheduler with regards to predicates then CA always leave nodes that can accommodate pods from the just-removed machine alive for 10 min. However, the experience shows that there can be bugs or unexpected behavior in other components that can severely affect CA.
