### ISSUE TITLE
Only Approved PRs to Be Merged After Feature Freeze

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/contrib#1924]
No new features should be merged after Feature Freeze (see the exceptions doc), and we should enforce this using the mungebot, so that it does not have to be manually monitored.  

I propose we do the following:
- [ ] Add a new flag that indicates the current release
- [ ] Add a new flag that indicates if we're in feature freeze period
- [ ] Add a new label (releaseCzarApproved) that indicates Saad (and future releaseCzars) have given the ok for it to get merged
- [ ] Create a new munger that checks if we're in a feature freezer period.  If so, check if the milestone set on the PR matches the current one and if the releaseCzarApproved label has been applied.  Only merge the PR if both conditions are met

WDYT?

@apelisse @saad-ali @pwittrock

**Comment by eparis** [comment]
This makes sense at the very end of the bug fix period, but right after feature freeze there are so many bug fixes done that blocking on one person isn't reasonable.

Since the same people who can set the 1.x milestone can set the 'releaseCzarApproved' label I'm not sure why we need the distinction for most of the cycle. We can already only merge things with the specified 1.x milestone.

As we get close to release (post Beta?) maybe this makes sense. Has it really been a big problem in the past?

**Comment by saad-ali** [comment]
> This makes sense at the very end of the bug fix period, but right after feature freeze there are so many bug fixes done that blocking on one person isn't reasonable.

> As we get close to release (post Beta?) maybe this makes sense. Has it really been a big problem in the past?

Maybe enforce it in the last three weeks? @pwittrock was the last release czar and can comment on how much of a problem it was in the past. My understanding is that this will automate manually having to monitor the merge queue for unexpected changes getting in. Less manual work is better.

> Since the same people who can set the 1.x milestone can set the 'releaseCzarApproved' label I'm not sure why we need the distinction for most of the cycle. We can already only merge things with the specified 1.x milestone.

Right, since the set of people that can modify the milestone is the same as the set of people that can add a label, we should not use a label for approval, and instead use a comment from a white-listed group of Github handles (e.g. "approved for merge by czar")).

**Comment by eparis** [comment]
@saad-ali if someone other than you adds the 'approved by release czar' label we know that in the github history and we can use social behavior changes (like removing their write perms) to stop such behaviors.I think getting more things/lists in tools correct is brittle.

If such a label has `czar` in the name it would certainly be more clear than the milestone that people shouldn't be setting it themselves...

**Comment by pwittrock** [comment]
@eparis 

For context I suggested this to Saad a number of weeks back.  I suggested this because for 1.4 I manually monitored the merge queue and audited it for obvious features every 3-4 hours.  I saw a lot of pure feature additions go into the queue after feature freeze and had to manually kick most of them out.  Some I wasn't able to get to in time, and they got merged.  Some were very obviously brand new features.

I agree that enforcing only the release-czar is allowed to merge may be a bit heavy handed, and we can try social engineering techniques to make sure everyone knows what is expected and encourage the behavior we want.  At a minimum I would suggest the following:

- Enforce requiring an additional label beyond "lgtm" to merge PRs e.g. "bug" or "bug-fix".  The idea being that folks will be more hesitant to apply that label to things that are features.
- Require PR authors to put in the description a link to an issue describing the bug.  The goal here is to make it easy for Saad or an auditor to quickly identify which issue this is fixing.

I'll let Saad decide if he thinks we should do a weekly audit to make sure we are adding new features without approval.

WDYT?

**Comment by saad-ali** [comment]
We managed 1.5 without this. Some people did try to sneak stuff in, but @dims stayed on top of the submit queue, valiantly kicking back the masses.

**Comment by dims** [comment]
LOL @saad-ali

**Comment by idvoretskyi** [comment]
@grodrigues3 +1. I agree with this initiative (sorry, haven't seen this yet).
