### ISSUE TITLE
[service-loadbalancer] haproxy server check "inter" too short

### ISSUE THREAD

**Issue by Conky5** [kubernetes/contrib#1932]
The backend server port check `inter` value is set to 5 milliseconds: https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/template.cfg#L143

This results in servers being marked as down quite frequently since they cannot always complete the check within 5ms (this is on a gcp kubernetes 2 node cluster).

Example of haproxy logs from service-loadbalancer:

```
servicelb [ALERT] Server graphite/10.0.0.9:80 is DOWN, reason: Layer4 timeout, check duration: 5ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
servicelb [ALERT] Server graphite/10.0.0.9:80 is DOWN, reason: Layer4 timeout, check duration: 5ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
servicelb [EMERG] backend graphite has no server available!
servicelb [EMERG] backend graphite has no server available!
```

High frequency:

```
$ kubectl logs service-load-balancer-3qyxb --since 5m | grep 'Server graphite.* is DOWN, reason: Layer4 timeout' | wc -l
     935
```

Increasing `inter` to 2000ms (the default http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#inter) results in much more stable backends.

This behavior results in 503 responses from service-loadbalancer thinking backends are down.

I'm thinking the default time should be increased or should be configurable.

**Comment by Dmitry1987** [comment]
@Conky5 I'm surprised since October this is still the case (just installed this).  Wonder how others actually use it with such interval.. it's probably in development and no one tried yet to use it in real life scenario.
I guess our simple option is to rebuild the docker image from repo, with needed modifications in template and other files, and use that image instead of the default one provided in example rc.yml :)

**Comment by Dmitry1987** [comment]
it was meant to be 5s maybe instead of 5 millis :paintbrush:
