### ISSUE TITLE
Cluster-autoscaler: Scale up before pod becomes unschedulable

### ISSUE THREAD

**Issue by yissachar** [kubernetes/contrib#1958]
Currently the cluster autoscaler waits for a pod to become unschedulable for it will start bringing new nodes up. Since nodes can take a long time to bring up, the unschedulable pod will remain unschedulable for a while. The cluster has basically entered a bad state and is now working on recovering from it.

Instead of only reactively bringing up nodes, the cluster autoscaler should also proactively bring up nodes when possible. It can do this on a best effort basis, following some heuristics (possible configurable), e.g. when no node has 1GB of memory available bring up another node.

Unschedulable pods would still trigger a scale up, since it is not possible to guarantee that a node will always be started proactively based on the heuristics.

**Comment by hjacobs** [comment]
We (Zalando) also talked today about cluster autoscaler --- from my point something like "sum all requests" + configurable buffer (like 10% free memory extra) would be desirable.
The current cluster autoscaler has a pretty bad UX as it only acts when it's "already too late".

**Comment by hjacobs** [comment]
@yissachar not sure whether you run on AWS, but if you do: https://github.com/hjacobs/kube-aws-autoscaler provides an experimental autoscaler for Auto Scaling Groups with buffer support.

**Comment by mumoshu** [comment]
@hjacobs I guess I'm a bit late to the party but I like the idea of the configurable buffer!

I'd expect app delivery teams to be responsible to configure HPAs appropriately and an infrastructure team managing a k8s cluster to be responsible to configure CA appropriately, so that delivery teams don't need to have a "buffer" for each HPA per app 😃 To be short, IHMO, CA having the "buffer" feature is the way to for the overall ease of operations across teams.

Perhaps we can port [yours](https://github.com/hjacobs/kube-aws-autoscaler/blob/master/kube_aws_autoscaler/main.py#L205) to CA?

**Comment by mwielgus** [comment]
Closing in favor of #2251. Please continue the discussion there.
