### ISSUE TITLE
Cluster-autoscaler: handle unready nodes

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#2228]
### Introduction

Currently ClusterAutoscaler stops working when the number of nodes observed on the cloud provider side doesn’t match to the number of ready nodes on the Kubernetes side. This behavior was introduced in the first version of CA in order to prevent CA from breaking more the already broken cluster. However the client reported feedback indicated that this behavior is oftentimes suboptimal and leads to confusion. This document sketches how the problem of unready nodes will be solved in the next release of K8S.

### Use cases

The number of ready nodes can be different than on the mig side in the following situations:

* [UC1] A new node is being added to the cluster. The node group has been increased but the node has not been created/started/registered in K8S yet. On GCP this usually takes couple minutes. 
Indicating factors:
 -- There was a scale up in the last couple minutes.
 -- The number of missing node is at most the size of executed scale-up.
Suggested action: Continue operations, however include all yet-to-arrive nodes in all scale-up considerations.

* [UC2] A new node is being added to the cluster. The node has registered on the cluster but has not yet switched its state to ready. This should be fixed in couple seconds. Indicating factors:
 -- The unready node is new. CreateTime in the last couple minutes.
Suggested action: Continue operations, however include all yet-to-arrive nodes in all scale-up considerations.

* [UC3] A new node was added to the cluster but failed to start within the reasonable time. There is little chance that it will start anytime soon. Indicating factors:
 -- Node is unready
 -- CreateTime == unready NodeCondition.LastTransitionTime
Suggested action: Continue operations, however do not expand this node pool. The probable scenario is that the node will be picked by scale down soon.

* [UC4] A new node is being added to the cluster. However the cloud provider cannot provision the node within the reasonable time due to either no quota or technical problems. Indicating factors:
 -- The target number of nodes on the cloud provider side is greater than the number of nodes in K8S for the prolonged time (more than couple minutes) and the difference doesn’t change.
Suggested action: Reduce the target size of the problematic node group to the current size. 

* [UC5] A node is in an unready state for quite a while (+20min) and the total number of unready/not-present nodes is low (less than XX%). It could either not switched from unready to ready on node registration or something crashed on the node and could not be recovered. Indicating factors:
-- Node condition is unready and last transition time is >= 20 min.
-- The number of TOTAL nodes in K8S is equal to the target number of nodes on the cloud provider side. 
Suggested action: Include the node in scale down, although with greater (configurable) unneeded time.

* [UC6] Some nodes are being removed by cluster autoscaler. Indicating factor:
-- Node is unready and has ToBeRemoved taint.
Suggested action: Continue operations. Nodes should be removed soon.

* [UC7] The number of unjustified (not related to scale-up and scale-down) unready nodes is greater than XX%. Something is broken, possibly due to network partition or generic failure. Indicating factors: 
 -- >XX% of nodes are unready 
Suggested action: halt operations.

**Comment by mwielgus** [comment]
cc: @fgrzadkowski @jszczepkowski @piosz @mumoshu @andrewsykim @kubernetes/sig-autoscaling-misc

**Comment by jszczepkowski** [comment]
UC3 appears two times, for two different cases

**Comment by andrewsykim** [comment]
@mwielgus can you shoot me a message when the main code for this is ready? I don't mind beta testing it on some AWS clusters I'm running.

**Comment by mwielgus** [comment]
@andrewsykim Sure, probably early next week.

**Comment by philk** [comment]
I was testing out these changes (which totally fix an issue we've been having with spot instances in a group, so thank you!) and found a bug but not sure what the best way to fix it will be.

I was getting the log messages:
```
I0124 02:36:50.508141       1 cluster_autoscaler.go:313] 8 unregistered nodes present
```

Did some digging and found [getNotRegisteredNodes](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/clusterstate/clusterstate.go#L446) added some logging:

```
W0124 02:36:49.432285       1 clusterstate.go:451] A ProviderID is aws:///us-west-2c/i-0887029c6d9c57ea0
W0124 02:36:49.471646       1 clusterstate.go:455] A Node is i-016c0fc5668d72f0c
```

So the `!registered.Has(node)` on L#458 is comparing
`aws:///us-west-2c/i-0887029c6d9c57ea0 == i-016c0fc5668d72f0c`

which explains the log message. I didn't wait to find out but I assume they'd all get deleted when the unregistered node timeout hits.

I would just submit a PR for this but I'm not sure (design-wise) where this should live.
- Changing `AwsCloudProvider.Nodes()` to return provider id's seems wrong.
- I could use `node.Spec.externalID` (which is just the instance ID) but I don't know if that's true for the other providers and [externalID is deprecated](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2925).
- Adding special case handling for the provider ID for AWS seems wrong. And again, I don't know if the other providers follow the pattern `<ProviderName>://<ProviderRegion>/<ProviderSpecificNodeID>` though with that said, I feel like the other providers are failing since they should at least be in the format `<ProviderName>://<ProviderSpecificNodeID>` (unless they're returning that from their respective `Nodes()` calls.

**Comment by andrewsykim** [comment]
@mwielgus any progress on this? Any way I can help move this forward?

**Comment by mwielgus** [comment]
The feature seems to be completed. Closing the issue.
