### ISSUE TITLE
Cluster-autoscaler: resource slack for faster pod startup

### ISSUE THREAD

**Issue by rimusz** [kubernetes/contrib#2251]
hey there, we are happily using https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler on AWS, is any way that scaler can scale two nodes instead of one? sometimes our apps do not get deployed via Deis Workflow which checks for the app deployment status.

Basically to have some spare node in ASG.

cc @mwielgus

**Comment by ideahitme** [comment]
@rimusz it only makes sense if you have scaling down disabled afaik. Otherwise all your spare nodes will get removed shortly right after next autoscaling cycle. I am actually interested myself in how it would be possible to use cluster-autoscaler and have spare nodes simultaneously. (even with possible hacky ways or simple workarounds)

**Comment by rimusz** [comment]
cluster-autoscaler works fine, but having a spare node would help a lot with HPA, otherwise it takes 5-6 min on AWS to get new node provisioned and in some case using Deis Workflow app release does not proceed if there is no spare resources left

**Comment by mwielgus** [comment]
Currently it is not possible. There are couple problems/questions. 

* How would you define a spare node? Is a node used more than in, let's say, 20% still a spare node or a new one should be added? If it is not spare anymore and a new spare is need then this approach will have troubles with our current Kubernetes scheduling that tries to put pods on underutilized nodes (we want to change the scheduler logic for CA eventually anyway but for this feature we would have to do it ASAP).
* Should there be always 1 extra node or a configurable amount?
* If there are 2 node groups and one doesn't have any spares (due to reaching max size) should the other inherit the spare quota?
* Scale downs will become more tricky. Imagine that you have 2 nodes that use only 15% each (so can be considered as spare). If you remove one of them then its pods may (or may not) make the other one non-spare and a new spare will be required. 

Anyway, we can definitely consider implementing this feature once we have a clear vision of how it would exactly work.

**Comment by Raffo** [comment]
@mwielgus We were discussing basically the same "requirements" today. The idea would be to always have some "buffer capacity" to keep around, to be able to handle spikes quickly and to support our deployment strategy in which we always create a new deployment for an application and then change the number of instances of the new and old ones towards the new version. Running at optimal capacity in terms of costs (with usage as goal), clashes with this approach and it should somehow be possible to support.

**Comment by mwielgus** [comment]
One option would be to have placeholder pods that would live only inside of cluster autoscaler.

To be more precise have N "extra" pods, each requiring C amount of cpu and M amount of memory. The variables would be defined as:

```
G (granularity) = 5   
E (extra capacity percentage) = 10%
N = cluster_size * G
C = average_cpu_size * E / G
M = average_memory_size * E / G
```

With that there will be an always present in-cluster-autoscaler need for 
```
N * C = cluster_size * G * average_cpu_size * E / G =
= cluster_size  * average_cpu_size * E  = total_cpu * E
```` 
cpu and 
```
N * C = cluster_size * G * average_memory_size * E/G = 
= cluster_size * average_memory_size * E = total_memory * E
```` 
memory. That will influence all of the scale-up/scale-down decision but won't be present in scheduler, so the new pods will be able to pick the place of the placeholders and push the placeholders elsewhere (and make them trigger the scale-up/down)

Would that work for you (or let me know if the description is not clear enough)?

**Comment by Raffo** [comment]
The description is enough and even if it sounds a bit hacky, I guess it makes sense. What it is not clear to me is how you would "push the placeholders elsewhere".

**Comment by mwielgus** [comment]
The **SIMPLIFIED** flow inside the main CA loop looks like this:

1. Get all nodes `AN`.
2. Get all pods  and put it into `AP`.
3. Get unschedulable pods from `AP` and put `USP`.
4. Try to find some place for `USP` on `AN`. Remove pods `USP` that you can place somewhere.
5. Trigger scale up for the remaining `USP`, if needed.
6. If no scale up occurred consider some nodes for scale down. See if their pods would be placed on some other nodes if their current node was removed. 
7. Remove a node, if possible. 

So imagine that we add the extra placeholder pods `PP` to `AP` every loop. We also let them go to `USP`, but treat them in a slightly different way. If we can put `PP` on some node w actually put them there and consume the fee capacity for a moment. So the following steps will think that they are they are real, scheduled and running movable pods. If some part of `PP` cannot be scheduled it remains in `USP` among other "real" unschedulable pods. They can trigger scale up.

In the same way, during scale down considerations, cluster autoscaler treats `PP` as regular, replicated pods, and tries to find a place for them. If it cannot it means that scaling the node down would reduce the extra capacity below the desired level. 

I agree that this is hacky but for now it is the only way (i can think of) that can actually reasonably guarantee that X% of resources is instantly/always available for scheduling.

**Comment by Raffo** [comment]
Sounds good to me and while hacky it makes sense for now. Do you want me/us to take a shot at a possible implementation of this?

**Comment by mwielgus** [comment]
I'm still finishing the unready nodes handling in CA and touching lots of stuff around. So not at this very moment, probably in a week or so, when the dust settles. Help is always appreciated :).

**Comment by Raffo** [comment]
Well, then I'll keep watching the PRs here and try to understand when it's ready to start a first implementation :-)

**Comment by hjacobs** [comment]
Related: #1958

**Comment by hjacobs** [comment]
@rimusz I implemented some experimental cluster autoscaler for AWS Auto Scaling Groups which is purely based on summing up resource requests (i.e. it will scale up to the calculated number of nodes and not one by one): https://github.com/hjacobs/kube-aws-autoscaler

**Comment by rimusz** [comment]
hey @hjacobs I'm already watching your repo, going to try it out next week

**Comment by Raffo** [comment]
@mwielgus Any updates on this? It looks like the long refactor is over, would it be the right time now to implement such a functionality?

**Comment by mwielgus** [comment]
@Raffo  Yes. Lets start with some more detailed design.

**Comment by mumoshu** [comment]
Hi @mwielgus - Anything specific you'd like a more detailed design for?
As https://github.com/kubernetes/contrib/issues/2251#issuecomment-272909968 looks good to me, I can work on a POC of it and submit a PR in the new repo.

**Comment by Raffo** [comment]
@mumoshu That would be a "good enough" implementation at the beginning, but I think there are many different approaches out there and it's probably worth listing them and discuss them so that we can identify if there is something we should have and we are definitely missing. What do you think?

**Comment by mumoshu** [comment]
@Raffo Thanks for the reply 👍 
I guess I completely agree you on the parts you've mentioned above.

Perhaps only possible difference(?) is that I'd rather like to proceed with the "good enough" implementation for now and discuss about possible future improved designs asynchronously, so that:
* probably we can move things forward
* we can gather even more information to decide whether it actually works or not and the initial design was really wrong or not, which is IMHO necessary to improve the design

WDYT?

**Comment by Raffo** [comment]
It works for me, I can also review and help you with the implementation.

**Comment by mwielgus** [comment]
Closing in favor or https://github.com/kubernetes/autoscaler/pull/77.

**Comment by frankh** [comment]
Should issues be closed for PRs? Shouldn't they be linked?

Also, the PR was closed without merging, can we re-open the issue? (Or is there another issue for this?)
