### ISSUE TITLE
[nginx-ingress-controller] question: Handling Custom error pages

### ISSUE THREAD

**Issue by rithujohn191** [kubernetes/contrib#2285]
Is there a way to host custom html error pages without having to update the nginx config and just providing some sort of flag value? 

We are currently using (https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl) as the nginx config file.  

According to the documentation at https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#custom-errors, in case of an error the response is obtained from the default backend. I tried updating this default backend image to a custom image that serves error pages and noticed that the default nginx error pages still get hosted.

**Comment by aledbf** [comment]
Basically you just need to add `custom-http-errors: 503` in the configmap specified in the flag `--nginx-configmap`
and use a custom default backend.
(https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/configuration.md#allowed-parameters-in-configuration-config-map)

This is the example:
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/examples/custom-errors

This is the content from the custom default backend https://github.com/aledbf/contrib/tree/nginx-debug-server/images/nginx-error-server
(you can also use a static go binary to server files reading the headers)

**Comment by aledbf** [comment]
How it works:
when the controller renders the nginx.conf file iterates the error codes (customHttpErrors)[https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/nginx.tmpl#L402] and creates a custom location where the error code will be redirected.
In case of an error we use lua to make an internal request (this is not possible with plain nginx**) to the default backend using the headers, returning the custom page.

**Note: it works but it does not returns 200 instead of the error code. That's the reason of the internal request.


Any feedback or alternative to simplify this is welcome ;)

**Comment by rithujohn191** [comment]
Thank you for the quick response. Will follow up with some simplifications after I get it to work.

**Comment by hawksight** [comment]
Rather than posting a seperate issue. I'm having similar trouble when trying to direct to custom erro pages.

I am trying to redirect internal 500 errors to the default backend on /500 (/ goes to 404).

Using:
gcr.io/google_containers/nginx-ingress-controller:0.8.3

Where the `@custom_xxx` code is as follows in the template:
```
{{/* definition of templates to avoid repetitions */}}
{{ define "CUSTOM_ERRORS" }}
        {{ range $errCode := .customHttpErrors }}
        location @custom_{{ $errCode }} {
            internal;
            content_by_lua_block {
                openURL({{ $errCode }})
            }
        }
        {{ end }}
{{ end }}
```
I think thats standard from the time, my config map is as follows:
```
apiVersion: v1
data:
  custom-http-errors: "500"
kind: ConfigMap
...
```

In order to test have deployed the default backend service to a separate ingress rule, so when I test going to that service with `/500` url it should get redirected by nginx using the custom error function.

I've noticed the redirect is picked up, but instead of taking me to a 500 page, it always redirects to the `/` which 404's. Checked with one of our apps forcing a 500 as well, and it does redirect to default backend, just not picking up the right path.
I've been reviewing the function used from this commit:
https://github.com/kubernetes/ingress-nginx/pull/1020/files
https://github.com/kubernetes/ingress-nginx/blob/45b68c2160fc971c2b8a2286722351605d306f63/controllers/ext_nginx/rootfs/etc/nginx/lua/error_page.lua#L11-L22

Im wondering if this line is always redirecting things to `/` instead of `/{{ $errCode }}`

Had a brief look at 0.9.beta-15 code and can see that block is vastly different now and no longer uses the lua code - however seems the config is loaded differently and as we are also manually passing the nginx template, (and config map) to the RC, I not hugely comfortable upgrading the nginx version just for this.

Any advice if I can pass any headers to openURL's first argument to get it to redirect??
Most things I've tried have broken the lua code so far.

**Comment by chestack** [comment]
> **Note: it works but it does not returns 200 instead of the error code. That's the reason of the internal request.

@aledbf , is there a plan to fix it to return the original error code. In my case scenario, client need to retry(or do following work)based on the return code

**Comment by chestack** [comment]
we only need small change to return the original error code. https://github.com/kubernetes/contrib/issues/2917
