### ISSUE TITLE
[fluentd-gcp-image] add kubernetes_metadata_filter

### ISSUE THREAD

**Issue by Bekt** [kubernetes/contrib#2501]
Consider adding [kubernetes_metadata_filter](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter) into the fluentd-gcp-image Gemfile.

Some description of the use cases is described [here](https://github.com/fabric8io/docker-fluentd-kubernetes/blob/master/fluent.conf#L69).

**Comment by crassirostris** [comment]
@Bekt Thanks for your suggestion!

Do you agree that it's impossible to include all possibly useful plugins in this image? We're using this image for fluentd with Stackdriver Logging, its plugin performs metadata enrichment itself. This image was intended to be a template for others to change in the way they need in their project. For example, someone would like to export to Kafka, someone would like to enrich entries with full pod metadata. We have a PR for the k8s documentation, which adds an instruction for changing the list of plugins in the fluentd image, you can take a look at it there: https://github.com/kubernetes/kubernetes.github.io/pull/3004

WDYT, is documenting the process enough or do you think that we should including this plugin in the default installation anyway?

**Comment by Bekt** [comment]
@crassirostris thanks for the context. I was borderline on suggesting this plugin as default or not.

* I find the plugin very useful, but I can't speak for everyone. However, this specific plugin is common to all k8s users, whereas some other plugins such as Kafka are not.

* The PR you linked suggests to build a custom image. There is also an option to pass in a Gemfile to fluentd during runtime such as:

  ```
  gem install bundler && /run.sh --gemfile /etc/fluent/Gemfile ...
  ```

  where the Gemfile could be passed through a ConfigMap.

  There are both pros (no need for a custom image) and cons (runtime installation). I don't mind this approach, but for some reason, I cannot install the bundler inside of the fluentd-gcp-imge container. This is a topic for another discussion, but that would easily solve the adding additional fluentd plugins situation without a custom image.

Thoughts?

**Comment by crassirostris** [comment]
@Bekt Sorry, I was on Kubecon. Thanks for the insight! I will try to address your ideas, but in reverse order :)

> The PR you linked suggests to build a custom image. There is also an option to pass in a Gemfile to fluentd during runtime such as:

I certainly see the benefits in this kind of image. However, we had also the following reasons not to do it:

* Size of the image, because gem installation requires build tools like gcc, make and etc.
* Startup time, obviously
* The setup that you will have in you cluster will be non-deterministic, since the gem version are usually not fixed

Also, you rarely need to change the set of gems, in most cases you only need to build the custom image once. Overall, IMO, benefits do not overweight the drawbacks in most cases.

> I find the plugin very useful, but I can't speak for everyone. However, this specific plugin is common to all k8s users, whereas some other plugins such as Kafka are not.

Taking into consideration previous point and the fact that google cloud plugin is not greatly compatible with this plugin, you'll probably want to install another output plugin to use it with k8s metadata filter anyway. Does it make sense?

As a general note, you might have noticed that there's a HUGE mess with different version, images and approached to collect logs (even if it's only about fluentd), we're working on getting it straight, but that will take time. For now there's a number of working solution, none of which is a standard. I suggest first coming up with the vision for the logging and the place of this image in the vision, and then executing the concrete engineering decisions. Does it make sense? I encourage you to keep an eye on sig-intrumentation and logging proposals, we will need your input to make it better.

**Comment by Bekt** [comment]
Thanks for the insight and agree with your points. I will definitely keep an eye on further development.

Given there's not much going on in fluentd-gcp-image, I think a custom image won't be much of a maintenance overhead.
