### ISSUE TITLE
Missing vagrant-aws

### ISSUE THREAD

**Issue by ChenXiaoTemp** [kubernetes/contrib#2590]
Following error occurs when I run vagrant up in ansible/vagrant folder
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/shawn/Develop/WorkSpace/Kubernetes1/contrib/ansible/vagrant/Vagrantfile
Line number: 0
Message: LoadError: cannot load such file -- vagrant-aws

**Comment by dhodovsk** [comment]
It happened to me also when the vagrant-aws plugin wasn't installed, as it was recommended in README.md.
https://github.com/kubernetes/contrib/tree/master/ansible/vagrant#before-you-start

The issue was that I performed the plugin installation as root. Vagrant plugins are installed into home directory, so my regular user didn't have access to it.

Try to make sure you have vagrant-aws installed and with the right user.
