### ISSUE TITLE
scratch-debugger/debug.sh doesn't work anymore

### ISSUE THREAD

**Issue by niels-s** [kubernetes/contrib#2803]
The `scratch-debugger/debug.sh` script doesn't work anymore, I tried applying the fix suggested in #2728 but without any luck. 
It seems like it doesn't find the docker socket on the host node:

```
sh: /mnt/rootfs/usr/bin/docker: not found
```

I'm running k8s version 1.8.3 on GKE

Besides that the README.md is also outdated to pass along a namespace or a container name it you should use flags instead of positional params but that's a separate issue.

**Comment by ApsOps** [comment]
Facing the same problem.

To check, I started debug container with command `sleep 6000` and exec'd in it.
`ls` shows the docker binary but running it says not found.

```
$> ls -la /mnt/rootfs/usr/bin/docker
-rwxr-xr-x    1 root     root      15096620 Jan 10  2017 /mnt/rootfs/usr/bin/docker

$> /mnt/rootfs/usr/bin/docker
ash: /mnt/rootfs/usr/bin/docker: not found
```

**Comment by rajiteh** [comment]
Ran in to the same issue on a Container Linux box and issue turned out to be due to the fact that `/usr/bin/docker` is a shell script with the shebang `#!/bin/bash`. Not found is thrown because the debug container doesn't have bash in it. However, looking at the shell script further, it looks like it won't work with the way its mounted anyway.
