### ISSUE TITLE
service-loadbalancer does not work with kube dashboard

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#488]
I'm trying to use the service-loadbalancer to expose the kube dashboard [1]. I can curl the dashboard pod/svc ip from within the cluster. The haproxy.cfg file appears to be properly updated and I don't see any errors in the pod logs. I can hit the kube-dashboard service externally when using a NodePort. [2] provides more details of the issue.

[1] https://github.com/kubernetes/dashboard
[2] https://gist.github.com/danehans/fd1170fb6df98b47adb8

**Comment by aledbf** [comment]
@danehans how are you trying to access the dashboard? 
What's the output of `curl -v http://<node where slb is running>/kubernetes-dashboard`?

**Comment by bprashanth** [comment]
Is the dashboard using js that refers back to the source url, i.e is it requesting resources like: http://$host/some.js? If it is, it won't work because you came in on a url like http://$host/svcName/, and haproxy will reject request made for /some.js because it doesn't understand the url. 

Does the dashboard work if you simply change the type of the NodePort service to Type=LoadBalancer on a cloud like GCE or AWS (if that's possible)?

**Comment by danehans** [comment]
@aledbf I am accessing the dashboard as you describe, using a DNS name associated to the node IP where the service-loadbalancer is running. I have been successful with another test web app, but not the kube dashboard.

@bprashanth [1] is the dashboard source code. I am in the process of rebuilding my lab. When complete, I will retest and open an issue with kube/dashboard if the same issue arises. The dashboard works when I use NodePort. I can't use the LoadBalancer b/c my setup is baremetal.

[1] https://github.com/kubernetes/dashboard

**Comment by borg286** [comment]
I am also encountering this issue, but with https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md
It also uses javascript and assumes that <domain>/js... is accessible. I was thinking a subdomain would help, but on a bare metals solution I am entering the IP address of my VM directly.
