### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/contrib#499]
I have a random question about an error I'm getting. I'm doing some work in the service-loadbalancer project and have a build error. When I use the makefile build it's ok, just my IDE on OSX throws this error. 

Is there an update somewhere or flag I can set?

```
./service_loadbalancer.go:818: undefined: "k8s.io/kubernetes/pkg/util".NeverStop
./service_loadbalancer.go:819: undefined: "k8s.io/kubernetes/pkg/util".NeverStop
./service_loadbalancer.go:824: undefined: "k8s.io/kubernetes/pkg/util".Until
./service_loadbalancer.go:824: undefined: "k8s.io/kubernetes/pkg/util".NeverStop
```

**Comment by eparis** [comment]
your IDE is likely using the $GOPATH to find `k8s.io/kubernetes` instead of using godep to find the version of k8s.io/kubernetes inside `Gopath/_workspace/src/k8s.io/kubernetes`

You can either figure out how to get your IDE to use godep, or you can run `godep restore`, to overwrite the version of kubernetes in your GOPATH with the version that this expects.

**Comment by stevesloka** [comment]
Thanks so much @eparis that did the trick!
