### ISSUE TITLE
openstack plugin required when when using Virtualbox Plugin for Ansible Vagrant

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#638]
Vagrant spits out an error requiring the openstack plugin even if you don't use the openstack provider.

```
$ vagrant --version
Vagrant 1.7.4
```

**Comment by danehans** [comment]
cc @stephenrlouie

**Comment by rutsky** [comment]
I can confirm this issue.

Looks like it's not trivial (and maybe not even possible) to workaround this due to the nature of `Vagrantfile` execution: there is [no easy way](https://github.com/mitchellh/vagrant/issues/1867) to get current provider or to run some code for specific provider. Workaround that is used assumes configuration code is always run, but not always configuration changes are registered.

I think with current implementation of Vagrant there is no better solution than to document that OpenStack plugin should be explicitly installed (as done in #637).

**Comment by danehans** [comment]
@rutsky thanks for confirming. @eparis do you have any suggestions or do we just address the limitation as was done in https://github.com/kubernetes/contrib/pull/637?

cc @stephenrlouie

**Comment by rutsky** [comment]
FYI, here is discussion on the Vagrant mailing list about the issue of detecting provider in Vagrant: https://groups.google.com/forum/#!topic/vagrant-up/XIxGdm78s4I
Short summary: no proper solution found to run specific code for single provider, only hacks with manual parsing of command line arguments/setting provider with environment variables.

**Comment by danehans** [comment]
@eparis do you mind weighing in when you have a moment?

**Comment by eparis** [comment]
If the only option is to document it, lets document it. I'm FAR from an expert.
