### ISSUE TITLE
add `pre-ansibe` role to `common` role deps, add `common` role to other roles deps

### ISSUE THREAD

**Issue by rutsky** [kubernetes/contrib#671]
Initial discussion: https://github.com/kubernetes/contrib/pull/669#issuecomment-203120047

Currently `bin_dir` for Core OS is defined [`common` role](https://github.com/kubernetes/contrib/blob/6aaa2f148a5b1348422e9c6653b7c984273e93f1/ansible/roles/common/tasks/main.yml#L45), [`kubernetes` role](https://github.com/kubernetes/contrib/blob/0ba7c0a9076fd571f02214b4cde7ae92b65459d2/ansible/roles/kubernetes/tasks/main.yml#L16) and when #669 will be merged it will be defined in [`pre-ansible`](https://github.com/adamschaub/contrib/blob/coreos_python_bootstrap/ansible/roles/pre-ansible/tasks/main.yml#L23) too.
This multiple definition can be eliminated if `common` will depend on `pre-ansible`, and other roles will depend on `common` role (which seems logical to me).

Significant constraint: all roles must be run only once.

/cc: @eparis, @adamreese

**Comment by danehans** [comment]
@rutsky thank you for creating this issue. I was asking myself this question when I was working on the initial coreos PR. We need to have better deps between the roles and remove duplication.

/cc: @adamschaub

**Comment by ingvagabund** [comment]
I would avoid any dependency if possible. Currently, ``master`` and ``node`` roles depends on common. With introduction of dependency on ``pre-ansible``, you will run even more. Let's analyse the ``common``, ``pre-ansible`` and other roles to see, what is common and break all the facts initialization and other "one-time" tasks into more roles instead of keeping all of it inside ``common``. Of course, wherever it is reasonable.
