### ISSUE TITLE
Submit queue ui is borken

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/contrib#78]
/api says
```
json: unsupported type: <-chan struct {}
```
@lavalamp

**Comment by davidopp** [comment]
When I access it now I don't get an error but all the fields are blank (I just get the section headings).
I assume you are talking about http://submit-queue.k8s.io/

**Comment by lavalamp** [comment]
@brendandburns did you change something? I'll look at this later today if I
don't hear anything.

**Comment by brendandburns** [comment]
I didn't change anything since wed.  I'm looking at it now though...

**Comment by mikedanese** [comment]
Broken again?

**Comment by brendandburns** [comment]
Yeah, it's the same thing.  For the life of me I have no idea what is causing it.  The error is b/c we're trying to json serialize a channel object, but I have _no_ idea where that channel is stored, or what causes it to happen.

I bounced the job and it's back.  I'll add a health check so that it automatically restarts to stop the bleeding, but we should figure out why its happening.

**Comment by lavalamp** [comment]
Yeah, just FYI, the health check isn't catching this.

**Comment by brendandburns** [comment]
haven't added it yet :P
