### ISSUE TITLE
Nginx Ingress Controller - Allow scoping by selectors

### ISSUE THREAD

**Issue by bretthoerner** [kubernetes/contrib#847]
By my reading of the code (which could be wrong) the nginx-ingress-controller only allows you to "scope" your ingress objects by namespace.

I have a case where I'd like to run 2 nginx-ingress-controllers in the same namespace, each with different configuration. But within that single namespace each nginx-ingress-controller will "see" and use all ingress objects.

Does it make sense to allow for the label/selector pattern on ingress objects and nginx-ingress-controller deployments? This is something I'm willing to work on, but it's probably best someone verify my assumptions are correct here.

**Comment by aledbf** [comment]
@bretthoerner using `--watch-namespace` in the controller you can limit the limit the scope of Ingress objects to one namespace. With that flag you can run 2 controller in the same namespace with different configurations

**Comment by bretthoerner** [comment]
I tried that, but it seems to use the namespace of the Ingress object as the namespace where services are expected to be.

In other words, running `default/nginx-ingress-controller1` that's watching `ns1` for ingress objects... then `ns1/ingress-object1` that uses vhost to point to service `service1` resulted in an error that `ns1/service1` didn't exist. I tried using `default/service1` but it says it has to be a valid DNS name.

If that made any sense, and is considered a bug, then I can try working on fixing that.

**Comment by aledbf** [comment]
@bretthoerner `service1` must exists in the same `namespace` than the Ingress rule

**Comment by bretthoerner** [comment]
OK, so that's the cause for my original ticket. Do you think a label/selector use-case might make sense for some people?

For example, say I'd like to break down my namespaces into `production` and `development` (which makes the most sense for DNS, e.g. the simple name `svc` will point to `svc.production` in `production` and `svc.development` in `development`).

But now within `production` I want an Ingress endpoint for public services, and another for "internal" services that are not yet inside Kubernetes (likely the case for most companies). So that public internet users can hit `my.website.com` and non-Kubernetes services inside of AWS can hit `my.internal.service` (but the public internet can't). Am I doing it wrong? :)

**Comment by aledbf** [comment]
> Do you think a label/selector use-case might make sense for some people?

yes it makes sense. 
That being said I don't know if this feature should be implemented in the Ingress controller because is not "generic" or maybe not supported in some platform.

ping @bprashanth

**Comment by whereisaaron** [comment]
There is somewhat of a design double-standard here, because when using '--watch-namespace' the nginx controller still lets you target cross-namespace Services for TCP/UDP, but not cross-namespace Services for HTTP/HTTPS. This is because Ingress resources require a service name in the same namespace as the Ingress, but the configMaps used for TCP/UDP allows you to specify a Services using a 'namespace/service' syntax. (I gather it is planned for TCP/UDP proxy to be rolled into Ingress resources rather than use a configMap eventually, so you might lose this cross-namespace capability for TCP/UDP down the line.)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap-example
data:
  9000: "default/example-go:8080"
```

I suggest that the controller implementation could have configuration to optionally target label selector(s). Different controllers can then target different combinations of Ingress resources. An the Ingress resource (for all supported protocols) would still have to be in the same namespace as their Services.

The '--watch-namespace' option would limit the scope of label selectors (if any) to specified namespace (or ideally namespaces)

With this approach, the cross-namespace capability remains an implementation behavior of this nginx controller, and the Ingress resources don't break the namespace separation Ingress/Service resources.

This is I think want @bretthoerner wants, and I suggest he can have it by extending the implementation of the nginx controller to support label selectors for Ingress resources, rather than any change to the way Ingress resources select Services.

**Comment by bprashanth** [comment]
We discussed cross namespace ingress on https://github.com/kubernetes/kubernetes/issues/17088 

Till now the granularity of Ingress has been at the namespace boundry. If you want to target services across namespaces you can use the serviceloadbalancer: https://github.com/kubernetes/contrib/tree/master/service-loadbalancer. I think allowing cross namespace ingress will make isolation harder. Or rather, it makes enforcing the most common type of isolation (on a ns boundry) require an extra admission controller of some sort. I'm open to ideas, please comment on  https://github.com/kubernetes/kubernetes/issues/17088 for changes to how ingress behaves.

**Comment by abh** [comment]
For configurations with a number of related namespaces the current system requires either having the "cross namespace" logic in the upstream load balancer / HA-IP or it requires an upstream ingress point for each namespace, which seems wasteful in many cases.

**Comment by thockin** [comment]
This issue was moved to kubernetes/ingress#554
