### ISSUE TITLE
RFC: Ansible Vagrant Providers

### ISSUE THREAD

**Issue by atosatto** [kubernetes/contrib#975]
Given the work done by @adamschaub in #761 and all the other people involved in the review, I'm wondering which Vagrant providers do we actually need to support to allow an easy and agile development and testing of the Ansible codebase.

Right now, the Vagrantfile is really complex and difficult to maintain.
To simplify its structure, I believe that we could drop the support to the OpenStack and/or to the Libvirt providers focusing on providing an easy way to test the different operating systems supported by the codebase in Virtualbox (for local development and testing) and a popular public cloud provider like DigitalOcean, AWS or GCloud (for multiple masters and minions provisioning).

Personally, this change would perfectly fit my workflow. 
Right now I'm using Virtualbox for local development and DigitalOcean to test PR #761.

@eparis @ingvagabund @danehans @rutsky @adamschaub do you believe that this changes could fit your workflow? Are you using different providers for your daily development of the project?

Thank you for you comments. Actually, I'm also looking for suggestions and insides on the tools and workflows you adopt to work at the project. 😉

**Comment by adamschaub** [comment]
@atosatto Integrating a public cloud provider sounds like a great idea. Additionally, packet.net is an option for provisioning baremetal servers. They don't have any integration with vagrant yet, but ansible/ansible-modules-extras#1673 adds an ansible module that can be used to create baremetal servers using their REST APIs.

**Comment by danehans** [comment]
@atosatto +1 on simplifying the Vagrant providers to only vbox.

**Comment by atosatto** [comment]
@adamschaub @danehans thank you for the feedback.
I will definitively work on this and hopefully be able to submit to your review a RC version of the Vagrantfile in the next days.

I believe that this could also help up testing PR #761.

**Comment by rutsky** [comment]
The only complexity I see with Vagrantfile is that it is really hard to support **more than one** provider and do proper `switch` clause between them. This is [Vagrant limitation](https://github.com/mitchellh/vagrant/issues/1867); we can overcome this by adding hacks such as writing using provider in separate file (which is not "Vagrant-way", but should significantly simplify code).

Other issue with libvirt and openstack providers is that I never used those and not sure is they work at all in our Vagrantfile. IMO best way to resolve this issue is to add some kind of CI that will run Vagrant with libvirt/openstack in properly configured environments.

Besides that I don't think that current Vagrantfile is comlex and hard to maintain.
It's less than 300 lines long and pretty well separated by different providers.

While I used only VirtualBox in my workflow, I agree with @eparis: some work already has been done to support libvirt/openstack that still might be useful for some users, and if we will have more than one provider we will not win anything regarding code complexity.

I suggest to try to overcome Vagrant limitations with it's inability to get currently used provider at first.

**Comment by ingvagabund** [comment]
As @eparis says, I have always run the Vagrant together with libvirt provider. As I am ``vagrant`` consumer only, I have no idea if there is a way to simplify the ``300`` long ``Vagrantfile`` file.

At least, I would like to have a CI for ``Vagrant`` + ``libvirt`` combo so I can run it together with the current ansible CI.

**Comment by JPvRiel** [comment]
Agree with @eparis 

> I refuse to run random kernel modules and thus vbox is not an option/alternative

I also appreciate the libvirt provider and, while VBox is more popular (credit for being cross platform), it's a royal pain with DKMS when using UEFI Secure Boot (e,g, [DKMS do not work on systems with Secure Boot enabled](https://wiki.ubuntu.com/UEFI/SecureBoot/DKMS)).
